services:

  web-emulator:

    build:
      context: .
      dockerfile: docker/Dockerfile

    ports:
      - "8080:8080"

    volumes:
      - ./saves:/app/saves
      - ./roms:/roms:ro

    restart: unless-stopped